<!DOCTYPE html>
<html>
<body>

<h1>Editar Categoría</h1>

<form action="<?= BASE_URL ?>categorias/actualizar" method="POST">
    <input type="hidden" name="id" value="<?= $categoria->categoria_id ?>">

    <input type="text" name="nombre" value="<?= $categoria->nombre ?>" required>
    <br><br>

    <button type="submit">Actualizar</button>
</form>

<a href="<?= BASE_URL ?>categorias">Volver</a>

</body>
</html>
