<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Agregar Producto</title>
</head>
<body>

    <h1>Agregar nuevo producto</h1>

    <form action="/tpweb2/productos/guardar" method="POST">

        <label>Nombre:</label><br>
        <input type="text" name="nombre" required>
        <br><br>

        <label>Precio:</label><br>
        <input type="number" step="0.01" name="precio" required>
        <br><br>

        <label>Categoría:</label><br>
        <select name="categoria_id" required>
            <?php foreach ($categorias as $categoria): ?>
                <option value="<?= $categoria->categoria_id ?>">
                    <?= $categoria->nombre ?>
                </option>
            <?php endforeach; ?>
        </select>
        <br><br>

        <button type="submit">Guardar producto</button>
    </form>

    <br>
    <a href="/tpweb2/productos">Volver al catálogo</a>

</body>
</html>