<!DOCTYPE html>
<html>
<body>

<h1>Login</h1>

<?php if (!empty($error)): ?>
    <p style="color:red;"><?= $error ?></p>
<?php endif; ?>

<form action="<?= BASE_URL ?>auth" method="POST">
    <input type="text" name="email" placeholder="Usuario" required>
    <br>
    <input type="password" name="password" placeholder="Contraseña" required>
    <br>
    <button type="submit">Login</button>
</form>

</body>
</html>
