<?php if (session_status() != PHP_SESSION_ACTIVE) session_start(); ?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Catálogo</title>
</head>
<?php if (session_status() != PHP_SESSION_ACTIVE) session_start(); ?>

<div>
    <?php if (isset($_SESSION['USER_ID'])): ?>
        <a href="<?= BASE_URL ?>logout">Cerrar sesión</a>
    <?php else: ?>
        <a href="<?= BASE_URL ?>login">Login</a>
    <?php endif; ?>
</div>

<hr>
<body>

    <h1><?= $titulo ?></h1>

    <?php if ($vieneDeCategoria): ?>
        <a href="<?= BASE_URL ?>categorias">Volver a categorías</a>
        <br>
        <a href="<?= BASE_URL ?>productos">Volver al catálogo</a>
    <?php else: ?>
        <a href="<?= BASE_URL ?>categorias">Ver por categorías</a>
    <?php endif; ?>

    <hr>
    <?php if (isset($_SESSION['USER_ID'])): ?>
    <a href="<?= BASE_URL ?>productos/crear">Agregar producto</a>
    <?php endif; ?>

    <ul>
        <?php foreach ($productos as $producto): ?>
            <li>
                <strong><?= $producto->nombre ?></strong> 
                - $<?= $producto->precio ?> 
                <br>

                <small>Categoría: <?= $producto->categoria_nombre ?></small>
                <br>

                <a href="<?= BASE_URL ?>productos/ver/<?= $producto->producto_id ?>">
                    Ver detalle completo
                </a>
                <br>

                <?php if (isset($_SESSION['USER_ID'])): ?>
                    
                    <a href="<?= BASE_URL ?>productos/editar/<?= $producto->producto_id ?>">
                        Editar
                    </a>
                    <br>

                    <a href="<?= BASE_URL ?>productos/eliminar/<?= $producto->producto_id ?>"
                       onclick="return confirm('¿Seguro que querés eliminar este producto?');">
                       Eliminar
                    </a>

                <?php endif; ?>

            </li>
            <hr>
        <?php endforeach; ?>
    </ul>

</body>
</html>
